name: Run 7 e mean

on:
  push:
    branches:
      - main
      
jobs:
  run_game:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run game
      run: python docs/app.py

    - name: Open browser
      if: success()
      run: xdg-open http://127.0.0.1:5000

