name: Run 7 and a Half

on:
  push:
    branches:
      - main

jobs:
  run_game:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Flask

    - name: Run the game
      run: |
        cd docs  # Mudando para o diretório docs
        python app.py
