name: Run Game

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask

      - name: Run Flask app
        run: |
          python docs/app.py &
          sleep 5
        shell: bash

      - name: Download and extract Ngrok
        run: |
          Invoke-WebRequest -Uri 'https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip' -OutFile 'ngrok.zip'
          Expand-Archive -Path 'ngrok.zip' -DestinationPath '.' -Force
        shell: powershell

      - name: Get Ngrok Tunnel URL
        id: ngrok
        run: |
          .\ngrok.exe http 5000 &
          sleep 10
          $url = Invoke-RestMethod http://localhost:4040/api/tunnels | Select-Object -ExpandProperty tunnels | Where-Object { $_.proto -eq "http" } | Select-Object -ExpandProperty public_url
          echo "::set-output name=url::$url"
        shell: powershell

      - name: Open browser
        if: success()
        run: start "" "${{ steps.ngrok.outputs.url }}/game.html"
